services:
  postgres:
    image: postgres:15
    container_name: airflow_postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    networks:
      - kraken
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: airflow_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - kraken
    volumes:
      - redis_data:/data

  airflow-webserver:
    image: apache/airflow:2.9.2
    container_name: airflow_webserver
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    entrypoint: 
      - /bin/bash
      - -c
      - |
        airflow db migrate &&
        airflow users create --username admin \
                            --firstname Admin \
                            --lastname User \
                            --role Admin \
                            --email admin@example.com \
                            --password #Suc3ss0! &&
        exec airflow webserver
    networks:
      - kraken

  airflow-scheduler:
    image: apache/airflow:2.9.2
    container_name: airflow_scheduler
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - kraken

  airflow-worker:
    image: apache/airflow:2.9.2
    container_name: airflow_worker
    restart: always
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
    command: celery worker
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - kraken

  airflow-init:
    image: apache/airflow:2.9.2
    container_name: airflow_init
    depends_on:
      - postgres
      - redis
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://airflow:airflow@postgres/airflow
    command: db init
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    networks:
      - kraken

  mysql-rdbms:
    image: mysql:latest
    container_name: mysql_rdbms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: #Suc3ss0!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kraken

  briefer-cloud:
    image: briefercloud/briefer
    container_name: briefer_cloud
    ports:
      - "3000:3000"
    volumes:
      - briefer_data:/var/lib/postgresql/data
      - briefer_jupyter:/home/jupyteruser
      - briefer_home:/home/briefer
    networks:
      - kraken

  minio:
    image: minio/minio:latest
    container_name: minio_storage
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    networks:
      - kraken
    command: server --console-address ":9090" /data

  spark-master:
    image: bitnami/spark:latest
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077"  # Porta do Spark Master
      - "8081:8080"  # Interface Web do Spark Master
    networks:
      - kraken

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - kraken

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter_notebook
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - kraken

networks:
  kraken:
    driver: bridge

volumes:
  dags:
  logs:
  plugins:
  postgres_data:
  redis_data:
  mysql_data:
  briefer_data:
  briefer_jupyter:
  briefer_home:
  minio_data:
