services:

  mysql-rdbms:
    image: mysql:latest
    container_name: mysql_rdbms
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Suc3ss0!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - kraken

networks:
  kraken:
    driver: bridge

volumes:
  mysql_data:
