services:

  storage-minio:
    image: minio/minio:latest
    container_name: storage_minio
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: Suc3ss0!
    volumes:
      - minio_data:/data
    networks:
      - kraken
    command: server --console-address ":9090" /data

networks:
  kraken:
    driver: bridge

volumes:
  minio_data:
