services:

  spark-master:
    image: bitnami/spark:latest
    container_name: spark_master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
    ports:
      - "7077:7077"
      - "8081:8080"
    networks:
      - kraken

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark_worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - kraken

  spark-jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter_notebook
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    ports:
      - "8888:8888"
    volumes:
      - ./spark/notebooks:/home/jovyan/work
    depends_on:
      - spark-master
      - spark-worker
    networks:
      - kraken

networks:
  kraken:
    driver: bridge

volumes:
  spark_notebooks: